os: Visual Studio 2017
version: 1.0.{build}
configuration: Release
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
pull_requests:
  do_not_increment_build_number: true
init:
- ps: |
    if ($env:APPVEYOR_REPO_TAG -eq $true -and $env:APPVEYOR_REPO_TAG_NAME  -match "^v\d+\.\d+\.\d+(-(?<prerelease>[\w\d]+))?$")
    {
        $env:TaggedForRelease = $true
        $env:TaggedForPreRelease = $matches.prerelease -ne $null
        $relName = if ($env:TaggedForPreRelease) { "PreRelease" } else { "Release" }
        Add-AppveyorMessage "Tagged For $($relName): $($env:APPVEYOR_REPO_TAG_NAME)" -details $env:APPVEYOR_REPO_COMMIT
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME".Substring(1)
    }
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- dotnet --info
- dotnet restore
build_script:
- dotnet build -c %CONFIGURATION%
artifacts:
- path: .\SodaPop.RazorPagesSitemap\**\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 2W45hY3MjOovAzfb2U7kTGDndF1Jxqzao/47TP9eEFQ+kqNTlHktUFgHkGkWsHKO
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    TaggedForRelease: true
    #TaggedForPreRelease : false
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  prerelease: $(TaggedForPreRelease)
  description: 'Release of $(APPVEYOR_REPO_TAG_NAME)'
  auth_token:
    secure: uLTEBGoagOuXDvbSbUqHe2k/7Oyk4lttpWKHBn4mRdSiZP6aCB9MMybins2dQLCZ
  artifact: /.*\.nupkg/
  on:
    TaggedForRelease: true
